language: python
dist: bionic
cache: pip

install:
 - pip3 install pylint bandit mccabe
 - pip3 install -r requirements.txt

script:
 - find . -name "*.py" -exec python3 -m py_compile '{}' \;
 - find . -name "*.py" -exec pylint '{}' + || if [ $? -eq 1 ]; then echo "you fail"; fi
 - find . -name "*.py" -exec python3 -m mccabe --min 3 '{}' + || if [ $? -eq 1 ]; then echo "you fail"; fi
 - bandit -r .
